#!/usr/bin/env bash

defaults_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
defaults_repo_root="$(cd "${defaults_script_dir}/../.." && pwd)"

DEFAULT_IMAGE_REPOSITORY="asterinas/coco"
DEFAULT_KATA_RELEASE_REPOSITORY="asterinas/kata-containers"
DEFAULT_KATA_VERSION="3.28.0-20260423"
DEFAULT_GUEST_COMPONENTS_REPOSITORY="https://github.com/confidential-containers/guest-components"
DEFAULT_GUEST_COMPONENTS_REF="v0.18.0"
DEFAULT_PAUSE_IMAGE_REPOSITORY="docker://registry.k8s.io/pause"
DEFAULT_PAUSE_IMAGE_VERSION="3.10"
DEFAULT_RESOLV_CONF_NAMESERVER="8.8.8.8"

VERSION="${VERSION:-$(<"${defaults_repo_root}/VERSION")}"

IMAGE_REPOSITORY="${IMAGE_REPOSITORY:-${DEFAULT_IMAGE_REPOSITORY}}"
KATA_VERSION="${KATA_VERSION:-${DEFAULT_KATA_VERSION}}"
KATA_RELEASE_REPOSITORY="${KATA_RELEASE_REPOSITORY:-${DEFAULT_KATA_RELEASE_REPOSITORY}}"
GUEST_COMPONENTS_REPOSITORY="${GUEST_COMPONENTS_REPOSITORY:-${DEFAULT_GUEST_COMPONENTS_REPOSITORY}}"
GUEST_COMPONENTS_REF="${GUEST_COMPONENTS_REF:-${DEFAULT_GUEST_COMPONENTS_REF}}"
PAUSE_IMAGE_REPOSITORY="${PAUSE_IMAGE_REPOSITORY:-${DEFAULT_PAUSE_IMAGE_REPOSITORY}}"
PAUSE_IMAGE_VERSION="${PAUSE_IMAGE_VERSION:-${DEFAULT_PAUSE_IMAGE_VERSION}}"
RESOLV_CONF_NAMESERVER="${RESOLV_CONF_NAMESERVER:-${DEFAULT_RESOLV_CONF_NAMESERVER}}"
KATA_RELEASE_TAG="${KATA_RELEASE_TAG:-${KATA_VERSION}-asterinas}"
COCO_RELEASE_TAG="${COCO_RELEASE_TAG:-v${VERSION}}"
