apiVersion: v1
kind: Pod
metadata:
  name: alpine-kata-qemu-tdx
spec:
  runtimeClassName: kata-qemu-tdx-asterinas
  containers:
    - name: alpine
      image: docker.io/library/alpine:3.22
      command: ["sleep", "infinity"]
