apiVersion: v1
kind: Pod
metadata:
  name: alpine-kata-qemu-coco-dev
spec:
  runtimeClassName: kata-qemu-coco-dev-asterinas
  containers:
    - name: alpine
      image: docker.io/library/alpine:3.22
      command: ["sleep", "infinity"]
