[hypervisor.qemu]
path = "/usr/local/qemu/bin/qemu-system-x86_64"
kernel = "/opt/coco/prebuilt/asterinas-coco/aster-kernel-osdk-bin.qemu_elf"
initrd = "/opt/coco/prebuilt/asterinas-coco/kata-containers-initrd.img"
image = ""
machine_type = "q35"
rootfs_type = "ext4"
enable_annotations = ["enable_iommu", "virtio_fs_extra_args", "kernel_params", "default_vcpus", "default_memory", "cc_init_data"]
kernel_params = "console=ttyS0 earlyprintk=serial,ttyS0,115200 agent.debug_console agent.debug_console_vport=1026 ostd.log_level=warn cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1"
cpu_features = "pmu=off"
default_vcpus = 1
default_bridges = 1
default_memory = 8192
disable_block_device_use = false
block_device_driver = "virtio-scsi"
block_device_aio = "io_uring"
enable_debug = true

[agent.kata]
enable_debug = true
debug_console_enabled = true

[runtime]
enable_debug = true
create_container_timeout = 300
internetworking_model = "none"
disable_new_netns = true
use_qemu_user_net = true
